# Replace this with your own database configuration.

development:
  adapter: sqlite3
  database: blog_development

test:
  adapter: sqlite3
  database: blog_test

production:
  adapter: mysql
  database: blog_production
  username: root
  password: 
  host: localhost
